# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyoc < Formula
  desc "A lazy terminal UI for OpenShift/Kubernetes clusters"
  homepage "https://github.com/katyella/lazyoc"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/katyella/lazyoc/releases/download/v0.2.2/lazyoc_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "6e72c6427afb8b36bc29d85216ec2ac6535a43f5e5dca8a654b0d2bb54e7428e"

      def install
        bin.install "lazyoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/katyella/lazyoc/releases/download/v0.2.2/lazyoc_0.2.2_Darwin_arm64.tar.gz"
      sha256 "b4765048e35dafef236c9c975f6faf635659ccccd59aa19ee631186e93224f88"

      def install
        bin.install "lazyoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/katyella/lazyoc/releases/download/v0.2.2/lazyoc_0.2.2_Linux_x86_64.tar.gz"
      sha256 "9e9bf3ed037e5c8e38cf2f1bde67a84bd1cceaddbfc9a783c471d6bd9de7d27a"
      def install
        bin.install "lazyoc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/katyella/lazyoc/releases/download/v0.2.2/lazyoc_0.2.2_Linux_arm64.tar.gz"
      sha256 "a6c1456f6abb3ecb7cbe931d72b551980498697f71106a5cdb79e48cdeac8ebc"
      def install
        bin.install "lazyoc"
      end
    end
  end

  test do
    system "#{bin}/lazyoc --version"
  end
end
